language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - ng lint
  - ng test --browsers ChromeHeadless --watch false
  - npm run build:explorer:testnet
  - npm run build:explorer:mainnet
